### ISSUE TITLE
Anyone help me how to solve this ?

### ISSUE THREAD

**Issue by bhaveshpadharia** [shaanhk/New-GithubTest#1]
Anyone help me how to solve this ?

`cv2.imshow('video2', frames)
                               ^
IndentationError: unindent does not match any outer indentation level
`

**Comment by PraveenNellihela** [comment]
This is because the last if statement has an indent, probably by mistake, and as a result, is outside the loop. If you add an indent for this if statement, as well as the break statement within that loop, your code will work. I will include the modified code below for convenience.

```
import cv2
cap = cv2.VideoCapture('video.avi')
car_cascade = cv2.CascadeClassifier('cars.xml')
while True:
    ret, frames = cap.read()
    gray = cv2.cvtColor(frames, cv2.COLOR_BGR2GRAY)
    cars = car_cascade.detectMultiScale(gray, 1.1, 1)
    for (x, y, w, h) in cars:
        cv2.rectangle(frames, (x, y), (x + w, y + h), (0, 0, 255), 2)
    cv2.imshow('video2', frames)

    if cv2.waitKey(33) == 27:
        break
cv2.destroyAllWindows()
```
